spring.application.name=criticaBackend

spring.datasource.url=jdbc:postgresql://dpg-d39eept6ubrc73ev8oi0-a.oregon-postgres.render.com:5432/critica?sslmode=require
spring.datasource.username=root
spring.datasource.password=Mpt7UZthDquJNwvPWBD8bMyA6iC0r1rm
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=5001

jwt.secret=L0LuZ4gLX9pVUyjo7hkfvup72EngczEnlqK/6dKmLJU=
