spring.application.name=criticaBackend

spring.datasource.url=jdbc:postgresql://ep-patient-wind-abizcfac-pooler.eu-west-2.aws.neon.tech/critica
spring.jpa.properties.hibernate.default_schema=public
spring.datasource.username=neondb_owner
spring.datasource.password=npg_3acGOEtkfl8g
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=5001

jwt.secret=L0LuZ4gLX9pVUyjo7hkfvup72EngczEnlqK/6dKmLJU=
spotify.client-id=aa4a0f6a16364d998bcca9c9e8d8909b
spotify.client-secret=5edf5f890ce24144a84374e2935a5b5e
