spring.application.name=criticaBackend

spring.datasource.url=jdbc:postgresql://ep-patient-wind-abizcfac-pooler.eu-west-2.aws.neon.tech/critica?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_3acGOEtkfl8g
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=5001

jwt.secret=L0LuZ4gLX9pVUyjo7hkfvup72EngczEnlqK/6dKmLJU=
